package com.wat.melody.plugin.aws.ec2.common;

import java.io.IOException;
import java.security.KeyPair;
import java.util.HashMap;
import java.util.Map;

import com.amazonaws.services.ec2.AmazonEC2;
import com.wat.melody.common.keypair.KeyPairName;
import com.wat.melody.common.keypair.KeyPairRepository;
import com.wat.melody.common.keypair.KeyPairRepositoryPath;
import com.wat.melody.plugin.aws.ec2.common.exception.AwsException;

/**
 * <p>
 * A {@link AwsKeyPairRepository} helps to create, store and destroy
 * {@link KeyPair} on the local File System and in Aws EC2.
 * </p>
 * 
 * <p>
 * A {@link AwsKeyPairRepository} enhance the {@link KeyPairRepostory} by
 * providing Local KeyPair synchronization with Aws KeyPairs.
 * </p>
 * 
 * <p>
 * A {@link AwsKeyPairRepository} is thread safe.
 * </p>
 * 
 * @author Guillaume Cornet
 * 
 */
public class AwsKeyPairRepository {

	private static Map<KeyPairRepositoryPath, AwsKeyPairRepository> REGISTERED_REPOS = new HashMap<KeyPairRepositoryPath, AwsKeyPairRepository>();

	public synchronized static AwsKeyPairRepository getAwsKeyPairRepository(
			AmazonEC2 ec2, KeyPairRepositoryPath keyPairRepositoryPath) {
		if (keyPairRepositoryPath == null) {
			throw new IllegalArgumentException("null: Not accepted. "
					+ "Must be a valid "
					+ KeyPairRepositoryPath.class.getCanonicalName() + ".");
		}
		if (REGISTERED_REPOS.containsKey(keyPairRepositoryPath)) {
			return REGISTERED_REPOS.get(keyPairRepositoryPath);
		}
		AwsKeyPairRepository kpr = new AwsKeyPairRepository(ec2,
				keyPairRepositoryPath);
		REGISTERED_REPOS.put(keyPairRepositoryPath, kpr);
		return kpr;
	}

	private KeyPairRepository _kpr;
	private AmazonEC2 _cnx;

	protected AwsKeyPairRepository(AmazonEC2 ec2, KeyPairRepositoryPath kppr) {
		setConnection(ec2);
		setKeyPairRepository(KeyPairRepository.getKeyPairRepository(kppr));
	}

	public AmazonEC2 getConnection() {
		return _cnx;
	}

	private AmazonEC2 setConnection(AmazonEC2 connection) {
		if (connection == null) {
			throw new IllegalArgumentException("null: Not accepted."
					+ "Must be a valid " + AmazonEC2.class.getCanonicalName()
					+ ".");
		}
		AmazonEC2 previous = getConnection();
		_cnx = connection;
		return previous;
	}

	public KeyPairRepository getKeyPairRepository() {
		return _kpr;
	}

	private KeyPairRepository setKeyPairRepository(KeyPairRepository kpr) {
		if (kpr == null) {
			throw new IllegalArgumentException("null: Not accepted. "
					+ "Must be a valid "
					+ KeyPairRepository.class.getCanonicalName() + ".");
		}
		KeyPairRepository previous = getKeyPairRepository();
		_kpr = kpr;
		return previous;
	}

	public synchronized boolean containsKeyPair(KeyPairName keyPairName) {
		return getKeyPairRepository().containsKeyPair(keyPairName);
	}

	public synchronized KeyPair createKeyPair(KeyPairName keyPairName,
			int size, String passphrase) throws AwsException, IOException {
		// Get/Create KeyPair in the underlying repository
		KeyPair kp = getKeyPairRepository().createKeyPair(keyPairName, size,
				passphrase);
		// Create/test KeyPair in Aws
		createKeyPairInAws(keyPairName, kp);
		return kp;
	}

	public synchronized void destroyKeyPair(KeyPairName keyPairName) {
		// Delete KeyPair in Aws
		AwsEc2Cloud.deleteKeyPair(getConnection(), keyPairName);
		// Delete KeyPair in the underlying repository
		getKeyPairRepository().destroyKeyPair(keyPairName);
	}

	private synchronized void createKeyPairInAws(KeyPairName kpn, KeyPair kp)
			throws AwsException {
		if (AwsEc2Cloud.keyPairExists(getConnection(), kpn)) {
			// when KeyPair is already in AWS, verify the fingerprint
			String fprint = KeyPairRepository.getFingerprint(kp);
			if (AwsEc2Cloud.compareKeyPair(getConnection(), kpn, fprint) == false) {
				throw new AwsException(Messages.bind(
						Messages.KeyPairEx_DIFFERENT, kpn,
						getKeyPairRepository().getKeyPairRepositoryPath()));
			}
		} else {
			// when KeyPair is not in AWS, import the public key
			String pubkey = KeyPairRepository.getPublicKeyInOpenSshFormat(kp,
					"Generated by Melody");
			AwsEc2Cloud.importKeyPair(getConnection(), kpn, pubkey);
		}
	}

}
